apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sample-zipcode-import-app-location
  description: Location to import all sample-zipcode-import-app catalog components
spec:
  targets:
    - ./.platform/*.yaml
